os:
  - linux

language: rust

node_js:
  - 10

env:
  - BUILD_NPM_PACKAGE=true

before_install:
  - npm install
  - npm run build

script:
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then npm run upload-binary || exit 0; fi;

notifications:
  email:
    on_success: never
