os:
  - linux

dist: xenial

language: node_js

node_js:
  - 10

cache:
  - npm: true
  - cargo: true

before_install:
  - ./.travis.sh

script:
  - npm test
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then yarn upload-binary || exit 0; fi;

notifications:
  email:
    on_success: never
